// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0VHaFBrTis5RkhHTjZBZVgyVlV0TkZ6ZDVMK3ZSNS81VlVKd080SUVFQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUi9QS2hFQ0xyd2RVMHlZSjRBeGY1WkxCNU93aU5EVGlhVHU5ek82QllEYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJtRXBlR0x0OWhDaEJIdmJQMzIyU2g2RVIybG50bTJyd2dZZEg3OTRUVFV3PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJrblpSY2tKakYzRWwxT29VNkxaQWQ5TXk2bnNtVklDdmNEOEFUUnpQbjB3PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFCUmZKYzBiL05yOWMzQUZqYyt1MG5sbGM5cmYvMk53TGViUGVrc2NDR1E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IngxY3g1L3RjWGZwRFBFbXhVUFRQbHhvME1nTWh5ZkpYSmJnUlJxL3ZTQWs9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVUtNWm9MUmd2d3M1SmdmbzRkNTg2bUtLeXI4OURKTjVzM2hGUlJ4T3ptVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQWZCYS9wZFFzTVgvcXhYNjVxbkJQWGIveEtFK3Y2QzhWa0FuSHNmYldUVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNoVUF3UVRJeE92Q1Nia1kwWlhwZFV0VUdnSVpRYkl6WU1FUUpWQzdKNjlMOG5pcnFzUTBMMEVqMEx2TkNDL2dhTUtkTkk5REhGbEZwdDdBbWVQK2dRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NTMsImFkdlNlY3JldEtleSI6IlkxS1F3SVJQd2JLVStJaDUydDZnWk1QaWpnM2lGcFJuZmlTUGVaTEk0U1U9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU1NzQ5NzE4MjQwQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjMyNzdBQTQyN0M5NThDRTNDOUY4QjgyM0JERTlGRTFEIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzU2ODc0OTV9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6Im8yaHNZVzBzUU95LUt2aFZOY2ZfemciLCJwaG9uZUlkIjoiN2Y4MmQ3MWMtMDQ5YS00NDk5LWI0MzQtYzBiOTI2MWM5ZjIzIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZTbWx2cWlzR0MzVVR0bkxLcUh0NmRKSEJ4MD0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjOTN5SUJ0c0Z6L1lSZVZjYjJjT3pmNEpHWFk9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiMlBRR0RRUUsiLCJtZSI6eyJpZCI6IjI1NTc0OTcxODI0MDozQHMud2hhdHNhcHAubmV0IiwibmFtZSI6Ikpva2Vy8J+njCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUC9hdXRZQ0VMbjYwYnNHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoidUw2aHhCZnRFbUlNcXVNWm4zbWM2WmxpcDk5NkE0SXh2RElvYXNmWTF6VT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiL3pTWnhmYXd0akdGNE54aWVFSU43STgzNS9Nd09BTmFpdVVSSXNHUXdMMnFvck1qVXByVStmT0lyWmg5QmNBbHdFRngrS2lRUlVSakFzNDV2ajZHRGc9PSIsImRldmljZVNpZ25hdHVyZSI6IlVkV3Z4Szg5Z3JIdG1ZMmFjdFBqWlMyaWVjZUU5c09TRGMySDdYU24wYnV3VXQwNmYvUGMwMmRIWjdIQk9OaHk3bVVmZFdUVElpSy9zQ2k3QmlHUGpnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU1NzQ5NzE4MjQwOjNAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYmkrb2NRWDdSSmlES3JqR1o5NW5PbVpZcWZmZWdPQ01id3lLR3JIMk5jMSJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczNTY4NzQ5MywibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFQV1EifQ==
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "©yessertech",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "255621995482",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
